### ISSUE TITLE
“数据保护”模块的漏洞，以及一些个人建议

### ISSUE THREAD

**Issue by Violet-Nonbloosom** [CTimet/BedrockTechnology#3]
## 描述
- “数据保护”在注册和修复时忽略方块所在的维度。
  利用这一点可以刷方块。
- 除此之外，“数据保护”缺少自动保存。
  虽然这不是漏洞，但这可以有效提升这一模块的可靠性。

## 漏洞复现过程
1. 在主世界维度某个位置（设为 $(x,y,z)$）注册要刷的粘液科技方块（如核反应堆），
2. 在下界（或者其他维度），坐标为 $(x,y,z)$ 的地方尝试修复方块（无论那个位置实际上是什么方块）。
3. 如此做后，提示“修复成功”，并获得对应方块。

## 期望的修改
- 在注册和修复时，将维度考虑在内。
- 添加自动保存及其相关设置（如自动保存的周期）。

## 运行环境
 - Minecraft Version: 1.18.2
 - CS-CoreLib Version:
 - Slimefun Version: （汉化）v2022.04-release
 - Plugin Version:

**Comment by CTimetbukii** [comment]
了解，已解决问题 ，下载最新版即可解决问题
